from typing import Any, Dict, Optional

class AppError(Exception):
    def __init__(self, message: str, details: Optional[Dict[str, Any]] = None):
        super().__init__(message)
        self.message = message
        self.details = details or {}

class KnowledgeError(AppError): ...
class ExtractionError(KnowledgeError): ...
class ContradictionError(KnowledgeError): ...
class EntityResolutionError(KnowledgeError): ...
class MemoryError(AppError): ...
class EvolutionError(MemoryError): ...
class IngestionError(AppError): ...
class UnsupportedFormatError(IngestionError): ...
class FileTooLargeError(IngestionError): ...
class LLMError(AppError): ...
class RateLimitError(LLMError): ...
class ContextLengthError(LLMError): ...
class BudgetExceededError(LLMError): ...
class GraphError(AppError): ...
class VectorError(AppError): ...
class DatabaseError(AppError): ...
